name: "Build"
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: ['**']

env:
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
    - uses: cachix/cachix-action@v10
      with:
        name: kubukoz
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Cache sbt
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/local
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
          ~/AppData/Local/Coursier/Cache/v1
          ~/Library/Caches/Coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
    - run: nix develop --command bash -c 'cd vscode-extension && yarn && yarn compile'
    - run: nix develop --command sbt test
    -
      name: release
      if: startsWith(github.ref, 'refs/tags/v')
      run: nix develop --command ./release.sh
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
