name: "Build"
on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]
    tags: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: cachix/install-nix-action@v23

      - uses: cachix/cachix-action@v12
        with:
          name: kubukoz
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Cache sbt
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/local
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      # This step isn't strictly necessary, but separating it means we can inspect its run time more easily.
      - name: Setup environment
        run: nix develop --command echo Environment ready

      - name: Server tests
        run: nix develop --command sbt ci

      - name: VS Code extension tests
        run: nix develop --command bash -c 'cd vscode-extension && yarn && SERVER_VERSION=$(cat ../.version) xvfb-run --auto-servernum yarn test'

      - name: Show extension test logs
        if: always() && job.status == 'failure'
        run: cat vscode-extension/fixture/smithyql-log.txt | tail --lines 1000
