name: "Build"
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: ['**']
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
    - run: nix develop --command sbt test fastOptJS
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
    - run: nix develop --command ./release.sh
