name: "Release plugin"
on:
  workflow_dispatch:

jobs:
  build:
    name: "Release plugin"
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: cachix/install-nix-action@v23

      - uses: cachix/cachix-action@v12
        with:
          name: kubukoz
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: release plugin
        run: nix develop --command ./release-plugin.sh
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
